IA:
  url: "https://b.url.bfg.com"
  login: "login"
  password: "password"
  phase_name_length: 18 # сколько символов в коде САП номенклатуры

# это как зацепиться к план-графику -- не меняем пока ничего
PLGR:
  ssh_host: '0.0.0.0'
  ssh_port: 22
  ssh_login: 'ssh_login'
  ssh_password: 'ssh_password'
  remote_address:
    - '0.0.0.0'
    - 5672
  local_address:
    - 'localhost'
    - 15672
  rabbit_user: 'user'
  rabbit_password: 'password'

# указываем что сбрасываем перед новым импортом:
#    чтоб затянуть новый план -- надо старый с текущей даты же сбросить
#    вот это для этого
pf-reset-data: []
#  - 1 # План BFG
#  - 2 # План ERP
#  - 3 # Факт выпуска
#  - 4 # Запуск
#  - 5 # Переплан

# это указываем что отправляем. Если что-то не надо отправлять --
#  комментируем строку
queues:
#  ca-department: export_departments
#  ca-work-center: export_ca_equipment
#  ca-assembly-element: export_entities
#  ca-technological-process: export_ca_routes
#  ca-transition: export_ca_phases
#  ca-operation: export_ca_operations
#  ca-stock: export_ca_zapasy
#  pf-department: export_departments
#  pf-assembly-element: export_entities
#  pf-transition: export_phases
#  pf-transition-time: export_phases_labor
#  pf-unfinished-production: export_pg_wip
#  pf-quantity-launch: export_bfg_launch
#  pf-quantity-plan-bfg: export_bfg_finish
#  pf-quantity-plan-erp: export_erp_finish
#  pf-quantity-actual: export_erp_fact
  ca-job-ssz: export_ca_daily_tasks_from_raport